_display_information:
  name: Approval Request
features:
  bot_user:
    display_name: My Bot
    always_online: true
oauth_config:
  scopes:
    bot:
      - app_mentions:read
      - channels:history
      - chat:write
      - commands
      - users:read
settings:
  event_subscriptions:
    request_url: https://your-ngrok-url.com/slack/events
    bot_events:
      - message.channels
      - app_mention
  interactivity:
    is_enabled: true
    request_url: https://your-ngrok-url.com/slack/interactions
  org_deploy_enabled: false
  socket_mode_enabled: false
  token_rotation_enabled: false
